librarian-org/librarian

src/app/App.tsx
src/app/components/Content/index.tsx
src/app/components/Content/styles.ts

feat: added content component

---

src/app/App.tsx
src/app/components/Card/index.tsx
src/app/components/Card/styles.ts
src/app/styles/styled.d.ts
src/app/styles/themes/dark.ts
src/app/styles/themes/light.ts

feat: added card component

---

src/electron/Menu.ts
src/locales/en-US/common.json
src/locales/pt-BR/common.json

feat: added documentation menu

---

src/electron/Menu.ts

feat: added about screen

---

package.json
src/app/App.tsx
src/app/components/Input/index.tsx
src/app/components/Input/styles.ts
src/app/components/Tooltip/index.tsx
src/app/components/Tooltip/styles.ts
src/app/styles/styled.d.ts
src/app/styles/themes/dark.ts
src/app/styles/themes/light.ts
yarn.lock

feat: added input component

---

package.json
src/app/App.tsx
src/app/components/AlertsPanel/index.tsx
src/app/components/AlertsPanel/style.ts
src/app/components/Shortcuts/styles.ts
src/app/components/StatusBar/index.tsx
src/app/components/StatusBar/styles.ts
src/app/components/Tabs/TabContent/styles.ts
src/app/components/ToastContainer/Toast/index.tsx
src/app/components/ToastContainer/Toast/styles.ts
src/app/components/ToastContainer/index.tsx
src/app/components/ToastContainer/styles.ts
src/app/hooks/toast.tsx
src/electron/Main.ts
src/locales/en-US/common.json
src/locales/pt-BR/common.json
yarn.lock

feat: added status bar, alert panel and toast

---

package.json
src/app/components/CreatableSelectInput/index.tsx
src/app/components/CreatableSelectInput/styles.ts
src/app/components/Input/styles.ts
src/app/components/PublisherSelect/index.tsx
src/app/components/PublisherSelect/styles.ts
src/electron/database/repository/RepositoryBase.ts
src/locales/en-US/common.json
src/locales/pt-BR/common.json
yarn.lock

feat: added publisher component

---

src/database/migration/1637774086085-create_user.ts
src/electron/database/models/User.schema.ts

Intend to fix user login to be an unique

fix: change user login to unique

---

src/database/migration/1642602439500-create_user_types.ts
src/database/migration/1642602508651-create_admin_user.ts

Intend to add the start user of librarian.
closes #121

feat: added migration to create user types and admin user

---

ormconfig.json

fix: typeorm config to new paths

---

src/app/components/Table/TablePagination/index.tsx
src/locales/en-US/common.json
src/locales/pt-BR/common.json

feat: table component translations

---

src/app/components/SelectInput/index.tsx
src/app/components/SelectInput/styles.ts
src/electron/database/models/User.schema.ts
src/electron/database/models/UserType.schema.ts

Add generic select input component

feat: select input component

---

src/app/components/UserSelect/index.tsx
src/app/components/UserSelect/styles.ts

feat: select user input component

---

src/electron/Menu.ts
src/locales/en-US/common.json
src/locales/pt-BR/common.json

feat: add website to help menu

---

package.json
src/app/@types/images.d.ts
src/app/App.tsx
src/app/components/Home/index.tsx
src/app/components/Home/styles.ts
src/app/components/Login/index.tsx
src/app/components/Login/styles.ts
src/app/components/StatusBar/index.tsx
src/app/hooks/auth.tsx
src/app/router/Guardian.tsx
src/app/router/index.tsx
src/electron/Main.ts
src/electron/database/repository/UserRepository.ts
src/locales/en-US/common.json
src/locales/pt-BR/common.json
webpack.rules.js
yarn.lock

feat: added login

---

src/app/components/Card/index.tsx
src/app/components/Card/styles.ts
src/app/components/Title/Create/index.tsx
src/app/components/Title/List/index.tsx
src/app/components/Title/Read/index.tsx
src/app/components/Title/Update/index.tsx
src/electron/Main.ts
src/electron/database/repository/TitleRepository.ts
src/locales/en-US/common.json
src/locales/pt-BR/common.json

- Added button to edit titles on title details screen and fix save button redirects

feat: added edit button on title screen

---

src/app/components/Person/List/index.tsx
src/app/components/Person/List/styles.ts
src/app/components/Person/Person.ts
src/electron/Main.ts
src/electron/database/repository/PersonRepository.ts

feat: person list

---

package.json
src/electron/index.css
webpack.plugins.js
yarn.lock

- Just added the Libarian font.

feat: added nunito font

---

src/app/components/Login/index.tsx
src/app/components/Login/styles.ts
src/app/components/Person/List/index.tsx
src/app/components/Person/Person.ts
src/app/components/Person/Update/index.tsx
src/app/components/Person/Update/styles.ts
src/app/components/Person/index.tsx
src/app/components/SelectInput/index.tsx
src/app/components/UserTypeSelect/index.tsx
src/electron/database/repository/PersonRepository.ts

- Added person update screen
- Refers #89

feat: update person screen

---

src/app/components/Borrow/index.tsx
src/app/components/TitleSelect/index.tsx
src/app/components/UserTypeSelect/index.tsx
src/app/hooks/useSettings.ts

- Added automatic borrow and return dates.

feat: automatic borrow and return dates

---

src/app/components/Title/Create/index.tsx
src/app/components/Title/Update/index.tsx
src/app/hooks/useBarcode.ts
src/locales/en-US/common.json
src/locales/pt-BR/common.json

- Added EAN13 validation ISBN.

feat: isbn validation

---

src/app/styles/global.ts

fix: fixed buttons colors problem

---

README.md
src/electron/database/repository/TitlePublisherRepository.ts

- Added filter for already borrowed title on borrow screen.
- Resolves #154

feat: added filter for already borrowed title on borrow screen

---

babel.config.js
jest.config.js
package.json
tests/electron/infra/I18NextAdapter.spec.ts
tsconfig.json
tsconfig.migration.json
yarn.lock

test: get i18n package languages

---

src/app/components/Borrow/index.tsx
src/app/components/Person/Create/index.tsx
src/app/components/Person/Update/index.tsx
src/app/components/Person/index.tsx
src/app/components/Settings/index.tsx
src/app/components/Tabs/index.tsx
src/app/components/Title/Create/index.tsx
src/app/components/Title/Update/index.tsx
src/app/components/Title/index.tsx
src/app/util/AppEventHandler.ts
src/common/AppEvent.ts
src/electron/data/protocols/Menu/MenuActionHandler.ts
src/electron/infra/menu/DefaultMenu.ts
src/electron/infra/menu/NativeMenuActionHandler.ts
src/locales/en-US/common.json
src/locales/pt-BR/common.json

feat: global save

---

src/app/components/Person/Update/index.tsx
src/app/components/Title/Update/index.tsx

- This fix clear name on update screen crash crash.

fix: clear name on update screen crash

---

src/electron/Main.ts
src/electron/data/protocols/Menu/MenuBuildTemplate.ts
src/electron/infra/menu/DefaultMenu.ts
src/electron/infra/menu/NativeMenuActionHandler.ts
src/electron/infra/resources/DefaultResources.ts

- Fix about screen crash on loading icon.

fix: about screen crash on loading icon

---

src/app/components/UserTypeSelect/index.tsx
src/app/hooks/auth.tsx
src/electron/infra/db/repositories/user/UserLoginRepository.ts

- Applied some user profile rules.
- Resolves #158.

feat: apply profile rules

---

src/app/components/AlertsPanel/index.tsx
src/app/components/AlertsPanel/style.ts
src/app/components/StatusBar/index.tsx
src/app/components/StatusBar/styles.ts
src/locales/en-US/common.json
src/locales/pt-BR/common.json

- Improvements on alerts list
- Resolves #164

feat: added alerts counter and improved alerts list

---

src/app/components/Person/List/index.tsx
src/app/components/Person/Read/index.tsx
src/app/components/SearchMenu/index.tsx
src/app/components/Title/Create/index.tsx
src/app/components/Title/List/index.tsx
src/app/components/Title/Update/index.tsx
src/electron/infra/db/repositories/index.ts
src/electron/infra/db/repositories/title/CheckTitleClassificationRepository.ts
src/electron/infra/listeners/ListenersConfigs.ts
src/locales/en-US/common.json
src/locales/pt-BR/common.json

- Classification validation
- Classification on list, 
- Can repeat same publisher on title screen

fix: classification validation, classification on list, can repeat same publisher on title screen

---

src/electron/LibrarianWindow.ts

- Starts Librarian maximized
- Resolves #169

feat: starting maximized

---

src/electron/data/protocols/Menu/MenuActionHandler.ts
src/electron/data/protocols/Resource/Resource.ts
src/electron/data/protocols/Resource/ResourceGetLogsPath.ts
src/electron/infra/menu/DefaultMenu.ts
src/electron/infra/menu/NativeMenuActionHandler.ts
src/electron/infra/resources/DefaultResources.ts
src/locales/en-US/common.json
src/locales/pt-BR/common.json

- Added menu to show log files to make easy for users send data to the Librariam team.
- Resolves #171 
-

feat: menu to show log files

---

README.md

docs: added latest release build badge
